# Generated by Django 4.1.3 on 2024-02-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='description',
            field=models.TextField(blank=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='reason',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
