# Generated by Django 4.1.3 on 2022-12-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "created_at",
                    models.TimeField(auto_now_add=True, verbose_name="Created"),
                ),
                ("updated_at", models.TimeField(auto_now=True, verbose_name="Updated")),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
