# Generated by Django 4.1.3 on 2022-12-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
    ]
